---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-poc
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: envs/dev/base/
    repoURL: https://github.com/saukumar95/argocd-preview-poc.git
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-kustomize
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true